In [42]:
%load_ext autoreload
%autoreload 2
%matplotlib inline
import pandas as pd
import edhec_risk_kit as erk
import numpy as np
import matplotlib
from scipy.optimize import minimize

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [43]:
hfi = erk.get_hfi_returns()
hfi

,Convertible Arbitrage,CTA Global,Distressed Securities,Emerging Markets,Equity Market Neutral,Event Driven,Fixed Income Arbitrage,Global Macro,Long/Short Equity,Merger Arbitrage,Relative Value,Short Selling,Funds Of Funds
date,,,,,,,,,,,,,
1997-01,0.0119,0.0393,0.0178,0.0791,0.0189,0.0213,0.0191,0.0573,0.0281,0.0150,0.0180,-0.0166,0.0317
1997-02,0.0123,0.0298,0.0122,0.0525,0.0101,0.0084,0.0122,0.0175,-0.0006,0.0034,0.0118,0.0426,0.0106
1997-03,0.0078,-0.0021,-0.0012,-0.0120,0.0016,-0.0023,0.0109,-0.0119,-0.0084,0.0060,0.0010,0.0778,-0.0077
1997-04,0.0086,-0.0170,0.0030,0.0119,0.0119,-0.0005,0.0130,0.0172,0.0084,-0.0001,0.0122,-0.0129,0.0009
1997-05,0.0156,-0.0015,0.0233,0.0315,0.0189,0.0346,0.0118,0.0108,0.0394,0.0197,0.0173,-0.0737,0.0275
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-07,0.0021,-0.0058,0.0093,0.0040,-0.0010,0.0055,0.0022,-0.0014,0.0067,-0.0021,0.0045,-0.0052,0.0018
2018-08,0.0024,0.0166,0.0002,-0.0277,0.0004,0.0011,0.0017,-0.0007,0.0035,0.0050,-0.0002,-0.0214,0.0015
2018-09,0.0034,-0.0054,0.0050,-0.0110,-0.0016,0.0032,0.0036,0.0006,-0.0023,0.0028,0.0018,0.0036,-0.0022
2018-10,-0.0073,-0.0314,-0.0158,-0.0315,-0.0129,-0.0257,-0.0023,-0.0096,-0.0402,-0.0080,-0.0109,0.0237,-0.0269
2018-11,-0.0068,-0.0053,-0.0193,0.0120,-0.0211,-0.0034,-0.0067,-0.0087,-0.0044,0.0119,-0.0063,-0.0021,-0.0071

In [44]:
# Q1:
gaussian_var = erk.var_gaussian(hfi["2000":]["Distressed Securities"],level=1,modified=False)
gaussian_var

0.03143017693928047

In [45]:
# Q2
mod_gaussian_var = erk.var_gaussian(hfi["2000":]["Distressed Securities"],level=1,modified=True)
mod_gaussian_var

0.04966909110627918

In [46]:
# Q3
hist_var = erk.var_historic(hfi["2000":]["Distressed Securities"],level=1)
hist_var

0.042642

In [50]:
ind = erk.get_ind_returns()
l = ['Books', 'Steel', 'Oil', 'Mines']
ind = ind["2013":"2017"][l]
ind

          Books   Steel     Oil   Mines
2013-01  0.0513  0.0428  0.0788  0.0059
2013-02 -0.0654 -0.0268  0.0052 -0.0756
2013-03  0.0778  0.0210  0.0209  0.0091
2013-04 -0.0029 -0.0441 -0.0129 -0.1057
2013-05  0.0479  0.0384  0.0307  0.0022
2013-06  0.0246 -0.0472 -0.0211 -0.0959
2013-07  0.1207  0.0697  0.0496  0.0002
2013-08 -0.0488 -0.0275 -0.0193  0.0459
2013-09  0.0626  0.0835  0.0189  0.0116
2013-10  0.0718  0.0838  0.0472  0.0534
2013-11  0.0021  0.0172  0.0098 -0.0558
2013-12  0.0775  0.0652  0.0290  0.0684
2014-01 -0.0712 -0.0547 -0.0703 -0.0643
2014-02  0.0673  0.0255  0.0571  0.0656
2014-03 -0.0075  0.0367  0.0251 -0.0064
2014-04 -0.0209  0.0065  0.0564  0.0294
2014-05 -0.0153 -0.0162  0.0096 -0.0217
2014-06  0.0880  0.0489  0.0416  0.0629
2014-07 -0.0160  0.0220 -0.0349  0.0193
2014-08  0.0264  0.0621  0.0225  0.0134
2014-09 -0.0729 -0.0479 -0.0798 -0.1077
2014-10  0.0328  0.0217 -0.0447 -0.0928
2014-11  0.0111 -0.0246 -0.1003 -0.0088
2014-12  0.0183 -0.0660  0.0058 -0.0640
2015-01 -0.0218 -0.0965 -0.0430 -0.0435
2015-02  0.0900  0.0377  0.0475  0.1473
2015-03  0.0056 -0.0272 -0.0252 -0.0696
2015-04 -0.0411  0.0405  0.0692  0.1262
2015-05  0.0193 -0.0381 -0.0502 -0.0530
2015-06 -0.0084 -0.0525 -0.0374 -0.0635
2015-07 -0.0290 -0.0821 -0.0894 -0.1310
2015-08 -0.0861 -0.0441 -0.0370 -0.0148
2015-09 -0.0532 -0.1059 -0.0563 -0.0607
2015-10  0.1221  0.0590  0.1252  0.0882
2015-11 -0.0117 -0.0089  0.0107 -0.0606
2015-12 -0.0617 -0.0265 -0.0973 -0.0646
2016-01 -0.0527 -0.0965 -0.0463 -0.0534
2016-02 -0.0094  0.0737 -0.0298  0.1223
2016-03  0.0690  0.1774  0.1085  0.1332
2016-04  0.0183  0.0986  0.0908  0.1577
2016-05 -0.0052 -0.0849 -0.0093 -0.0511
2016-06 -0.0032  0.0256  0.0266  0.0799
2016-07  0.0740  0.1359 -0.0288  0.0750
2016-08  0.0031 -0.0752  0.0141 -0.0977
2016-09 -0.0393  0.0244  0.0294  0.0216
2016-10 -0.1026 -0.0298 -0.0290  0.0080
2016-11  0.0816  0.2136  0.0953  0.1160
2016-12  0.0201 -0.0226  0.0220 -0.0177
2017-01  0.0164  0.0370 -0.0433  0.1241
2017-02 -0.0035  0.0919 -0.0232 -0.0841
2017-03 -0.0089 -0.0614 -0.0126 -0.0231
2017-04 -0.0078 -0.0050 -0.0278 -0.0119
2017-05 -0.0165 -0.0460 -0.0347 -0.0108
2017-06  0.0275 -0.0022 -0.0020 -0.0055
2017-07  0.0237  0.0131  0.0202  0.0861
2017-08 -0.0629  0.0165 -0.0526  0.0083
2017-09  0.0360  0.0372  0.1125 -0.0195
2017-10 -0.0183  0.0223  0.0023  0.0145
2017-11  0.1024 -0.0138  0.0289  0.0015
2017-12  0.0111  0.1319  0.0509  0.1151

In [57]:
er = erk.annualize_rets(ind, 12)
cov = ind.cov()
cov

          Books     Steel       Oil     Mines
Books  0.002720  0.001940  0.001637  0.001539
Steel  0.001940  0.004391  0.002122  0.003391
Oil    0.001637  0.002122  0.002697  0.002179
Mines  0.001539  0.003391  0.002179  0.005232

In [58]:
# Q4
EW_steel = 1/ind[l].shape[1]
EW_steel

0.25

In [67]:
# Q5 , Q6
msr_weights = erk.msr(0.1, er, cov)
(msr_weights.max(),l[msr_weights.argmax()])

(1.0, 'Steel')

In [68]:
# Q7
msr_weights

array([0.00000000e+00, 1.00000000e+00, 2.08166817e-17, 6.01949046e-16])

In [71]:
# Q8 , Q9
weight_gmv = erk.gmv(cov)
(weight_gmv.max(), l[weight_gmv.argmax()])

(0.47702487014389955, 'Books')

In [72]:
# Q10
weight_gmv

array([0.47702487, 0.        , 0.43411203, 0.0888631 ])

In [76]:
# Q11
ind = erk.get_ind_returns()
ind = ind["2018"][l]
vol_msr = erk.portfolio_vol(msr_weights,ind.cov())*(12**0.5)
vol_msr

0.21983988181484188

In [77]:
# Q12
vol_gmv = erk.portfolio_vol(weight_gmv,ind.cov())*(12**0.5)
vol_gmv

0.18973734520184568